version: '3.8'
services:
  ollama:
    build: .
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - llm-network
    restart: unless-stopped

  qdrant:
    image: 'qdrant/qdrant:latest'
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - qdrant_storage:/qdrant/storage:z
    networks:
      - llm-network

volumes:
  ollama_data:
  qdrant_storage:

networks:
  llm-network:
    driver: bridge